apiVersion: v1
kind: Service
metadata:
  name: {{ include "one-chart.fullname" . }}
  labels:
    {{- include "one-chart.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      nodePort: 30080
      protocol: TCP
      name: http
  selector:
    {{- include "one-chart.selectorLabels" . | nindent 4 }}
